@startuml class_association
!include plantuml.config

class Biblioteca {
  +nombre: String
  +direccion: String
  +telefono: String
  +libros: List<Libro>
}

class Libro {
  +titulo: String
  +autor: String
  +editorial: String
  +isbn: String
}

Biblioteca - Libro : tiene

title Asociación entre Clases

caption "Cada <b>Biblioteca</b> puede contener múltiples libros, y cada <b>Libro</b> puede\nestar asociado para una biblioteca específica"

note top of Biblioteca: Clase Fuente
note top of Libro: Clase Destino

@enduml